version: 2

defaults: &defaults
  working_directory: ~/repo/vue-test-utils
  docker:
    - image: circleci/node:6.13.0-stretch-browsers
restore_node_modules: &restore_node_modules
  restore_cache:
    name: Restore node_modules cache
    keys:
      - v1-dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - v1-dependencies-{{ .Branch }}-
      - v1-dependencies-
jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - *restore_node_modules
      - run:
          name: yarn --version
          command: yarn --version
      - run:
          name: yarn install
          command: yarn install
      - save_cache:
          name: Save dependencies cache
          key: v1-dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/
      - persist_to_workspace:
          root: ~/repo
          paths:
            - vue-test-utils/
  bootstrap:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - *restore_node_modules
      - run:
          name: yarn bootstrap
          command: yarn bootstrap
  build_test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - *restore_node_modules
      - run:
          name: yarn build:test
          command: yarn build:test
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - *restore_node_modules
      - run:
          name: yarn test
          command: yarn test
  test_version_2.0.8:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - *restore_node_modules
      - run: yarn test:compat "2.0.8"
  test_version_2.1.10:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - *restore_node_modules
      - run: yarn test:compat "2.1.10"
  test_version_2.2.6:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - *restore_node_modules
      - run: yarn test:compat "2.2.6"
  test_version_2.3.4:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - *restore_node_modules
      - run: yarn test:compat "2.3.4"
  test_version_2.4.2:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - *restore_node_modules
      - run: yarn test:compat "2.4.2"
  test_version_2.5.13:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - *restore_node_modules
      - run: yarn test:compat "2.5.13"
workflows:
  version: 2
  install-tests:
    jobs:
      - install
      - bootstrap:
          requires:
            - install
      - build_test:
          requires:
            - install
      - test:
          requires:
            - install
      - test_version_2.0.8:
          requires:
            - install
            - build_test
            - test
      - test_version_2.1.10:
          requires:
            - install
            - build_test
            - test
      - test_version_2.2.6:
          requires:
            - install
            - build_test
            - test
      - test_version_2.3.4:
          requires:
            - install
            - build_test
            - test
      - test_version_2.4.2:
          requires:
            - install
            - build_test
            - test
      - test_version_2.5.13:
          requires:
            - install
            - build_test
            - test
