version: 2
jobs:
  build:
    docker:
      - image: node:6
    working_directory: ~/repo

    steps:
      - checkout
      - run: yarn --version

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          - v1-dependencies-

      - run: npm install
      - run: yarn
      - run: yarn test
      - run: yarn test:compat
      - run: yarn test:coverage

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
