version: 2

defaults: &defaults
  working_directory: ~/repo/vue-test-utils
  docker:
    - image: vuejs/ci
restore_node_modules: &restore_node_modules
  restore_cache:
    name: Restore node_modules cache
    keys:
      - v1-dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}
jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - *restore_node_modules
      - run:
          name: remove vuepress from dependencies
          command: sed -i '/vuepress/ d' package.json
      - run:
          name: yarn --version
          command: yarn --version
      - run:
          name: yarn install
          command: yarn install
      - save_cache:
          name: Save dependencies cache
          key: v1-dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/
      - persist_to_workspace:
          root: ~/repo
          paths:
            - vue-test-utils/
  bootstrap:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - *restore_node_modules
      - run:
          name: yarn bootstrap
          command: yarn bootstrap
  build_test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - *restore_node_modules
      - run:
          name: yarn build:test
          command: yarn build:test
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - *restore_node_modules
      - run:
          name: yarn test
          command: yarn test
  test_compat:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - *restore_node_modules
      - run: yarn test:compat
workflows:
  version: 2
  install-tests:
    jobs:
      - install
      - bootstrap:
          requires:
            - install
      - build_test:
          requires:
            - install
      - test:
          requires:
            - install
      - test_compat:
          requires:
            - install
            - build_test
            - test
